language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/test_waiter_webapp

node_js:  
   - "12"

before_script:
  - psql -c 'create database  test_waiter_webapp;' -U postgres
  - psql -U postgres -d test_waiter_webapp -a -f table.sql

services:
  - postgresql

  